---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: nginx
  values:
    extraEnvVars:
      - name: FOO
        value: BAR  

